### ISSUE TITLE
Legend class in "statement-example" doesn't allow resize

### ISSUE THREAD

**Issue by Butanium** [CodinGame/codingame-game-engine#72]
## Wide format : color issue in dark mode only
<img src="https://user-images.githubusercontent.com/55806347/187475635-19ee8a51-d102-42c8-aaf6-5ed78c4762a8.png" width="40%">

## Tight format : text issue even in light mode
<img src="https://user-images.githubusercontent.com/55806347/187477839-c7930406-d443-484b-a6ea-95689c107bef.png" width="40%">

The problem comes from [this piece of code](https://github.com/Butanium/Clash-of-bits/blob/ce97bf62ff348c7d261e1df51cebd7e8adfd952a/config/statement_en.html.tpl#L298). Replacing `class=legend` by `style="padding: 10px"` fix the text problem, but in dark modes it becomes unreadable 

![image](https://cdn.discordapp.com/attachments/1014163208396873798/1014184349765214259/unknown.png)

I think the easiest solution would be to make the `statement-example` background theme sensitive

**Comment by Butanium** [comment]
@chickentuna I need this for my multiplayer submission. If nothing can be done about it / you don't have time to do it, I'll just stick with a normal image insertion. I just need to know 😶

**Comment by chickentuna** [comment]
@Butanium Have you tried overloading the height: property of the `<div class="legend">` tag?

e.g.

```html
<div style="height:auto;" class="legend">
```

**Comment by Butanium** [comment]
It doesn't fix the wide format issue, but it fixes the text issue in tight format.
![image](https://user-images.githubusercontent.com/55806347/189627296-d0b10306-9ae4-48ae-94bd-274f76b2259c.png)

The white background comes from the `statement-example` div, not the `legend` div if I understand correctly.

**Comment by chickentuna** [comment]
You are having this issue because the images are not intended to have different sizes. Have you considered reframing your example images to have the same dimensions?
If you cannot, I fear that the alternative is to keep hacking away at random css properties because I cannot work on changing the IDE layout right now

**Comment by Butanium** [comment]
OK, I thought a small change could make the `statement-example` theme sensitive.
If I can make it like this with some CSS properties, let me know.
Otherwise, I'll just use images of the same size then, thanks.

**Comment by Butanium** [comment]
![image](https://user-images.githubusercontent.com/55806347/190384251-12713b77-39a6-49fc-b216-622d3ca7c4b0.png)
Having the same size doesn't solve the issue as some descriptions are longer than others.

**Comment by chickentuna** [comment]
Oh, this looks like yet another instance of our sanitizer messing things up. I will endeavour to replace this sanitizer with something a little less aggressive

**Comment by CGjupoulton** [comment]
@Butanium After a closer look, it seems that the CSS actually was intended for all text blocks to have a fixed and equal height, which is why setting variable heights with height: auto causes this issue. I think this is an unnecessary limitation and have implemented your suggestion of extended the dark mode's css to the statement-example class. Fix will be online soon

**Comment by Butanium** [comment]
Nice, thanks a lot !
